version = 1
[approve]
auto_approve_usernames = ["dependabot"]

[merge]
require_automerge_label = false
blocking_labels = ["wip"]

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
include_coauthors = true
include_pull_request_author = true
include_pull_request_url = true

[update]
always = true
ignored_usernames = ["dependabot"]
