inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude: []

# Allow longer line length for bigger screens
Layout/LineLength:
  Max: 120
  StyleGuide: 'https://github.com/itsmycargo/rubocop-itsmycargo/blob/master/docs/Guide.adoc#maximum-line-length'

Style/Documentation:
  Enabled: false
  StyleGuide: 'https://github.com/itsmycargo/rubocop-itsmycargo/blob/master/docs/Guide.adoc#classmodule-documentation'

# Disable Rubocop disable comments (widely mis-used)
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true

# Severities: refactor, convention, warning, error and fatal.
Bundler:
  Severity: fatal

Gemspec:
  Severity: fatal

Layout:
  Severity: error

Lint:
  Severity: error

Metrics:
  Severity: error

Naming:
  Severity: error

Security:
  Severity: error

Style:
  Severity: error
