require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

# Allow longer line length for bigger screens
Layout/LineLength:
  Max: 120
  StyleGuide: 'https://github.com/mikian/itsmycargo/blob/master/docs/Guide.adoc#maximum-line-length'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# Allow Ignoring filename requirements for initializers
Naming/FileName:
  Exclude:
    - config/initializers/*.rb
  StyleGuide: 'https://github.com/mikian/itsmycargo/blob/master/docs/Guide.adoc#snake-case-files'

Style/Documentation:
  Enabled: false
  StyleGuide: 'https://github.com/mikian/itsmycargo/blob/master/docs/Guide.adoc#classmodule-documentation'

Style/MethodCalledOnDoEndBlock:
  Enabled: true

# RSpec
RSpec/MultipleExpectations:
  AggregateFailuresByDefault: true

RSpec/ExampleLength:
  Max: 8

RSpec/NestedGroups:
  Max: 4
