name: Version

on:
  push:
    paths-ignore:
      - 'lib/rubocop/itsmycargo/version.rb'
      - 'CHANGELOG.md'
    branches:
      - master

jobs:
  build:
    name: Bump
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: |
        git config --local user.email "dev-services@itsmycargo.com"
        git config --local user.name "ItsMyCargo"
    - run: bundle
    - run: rake bump:patch
    - run: git push --follow-tags
