name: Ruby Gems

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: |
        git config --local user.email "dev-services@itsmycargo.com"
        git config --local user.name "ItsMyCargo"
    - run: bundle
    - run: rake bump:patch
    - run: git push --follow-tags

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}

    - name: Publish to GitHub Package Registry
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        echo ":github: Bearer GH_TOKEN" >> $HOME/.gem/credentials
        gem build *.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/itsmycargo *.gem
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
